/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CtrlCaixa;
import Controller.CtrlCliente;
import Controller.CtrlVenda;
import DAO.Banco;
import DAO.MoedasDAO;
import DAO.TipoPagamentoDAO;
import Model.Cliente;
import Model.Moedas;
import Model.Notas;
import Model.Venda;
import java.awt.Color;
import java.awt.Insets;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author caiol
 */
public class FrmDinheiro extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmDinheiro
     */
    private Moedas moedas;
    private Notas notas;
    private Venda venda;
    
    Banco bd = new Banco();
    
    CtrlVenda ctrl = new CtrlVenda();
    Double totalEntrado = 0.0;
    public FrmDinheiro() {
        initComponents();
        //Retirar bordas
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        setBorder(new EmptyBorder(new Insets(0,0,0,0)));
    }

    public FrmDinheiro(Moedas moedas, Notas notas) {
        this();
        this.moedas = moedas;
        this.notas = notas;
        jLabel29.setVisible(false);
        lblValorPago.setVisible(false);
        spn005.setValue(moedas.getQtd5());
        spn01.setValue(moedas.getQtd10());
        spn025.setValue(moedas.getQtd25());
        spn05.setValue(moedas.getQtd50());
        spn1.setValue(moedas.getQtd1Real());
        
        spn2.setValue(notas.getQtd2());
        spn5.setValue(notas.getQtd5());
        spn10.setValue(notas.getQtd10());
        spn20.setValue(notas.getQtd20());
        spn50.setValue(notas.getQtd50());
        spn100.setValue(notas.getQtd100());
        
        
    }

    public FrmDinheiro(Venda venda) {
        this();
        this.venda = venda;
        lblValorPago.setText(String.format("%.2f", venda.getTipoPagamento().getValorDescontado()));
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner5 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spn2 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        spn5 = new javax.swing.JSpinner();
        spn10 = new javax.swing.JSpinner();
        spn20 = new javax.swing.JSpinner();
        spn50 = new javax.swing.JSpinner();
        spn100 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        lblTotalN = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        spn005 = new javax.swing.JSpinner();
        spn01 = new javax.swing.JSpinner();
        spn025 = new javax.swing.JSpinner();
        spn05 = new javax.swing.JSpinner();
        spn1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        lblTotalM = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblValorPago = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel1.setText("Dinheiro");

        spn2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn2StateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel2.setText("Total em notas:R$");

        jLabel26.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel26.setText("R$ 2,00:");

        jLabel23.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel23.setText("R$ 5,00:");

        jLabel24.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel24.setText("R$ 10,00:");

        jLabel25.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel25.setText("R$ 20,00:");

        jLabel27.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel27.setText("R$ 50,00:");

        jLabel28.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel28.setText("R$ 100,00:");

        spn5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn5StateChanged(evt);
            }
        });

        spn10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn10StateChanged(evt);
            }
        });

        spn20.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn20StateChanged(evt);
            }
        });

        spn50.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn50StateChanged(evt);
            }
        });

        spn100.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn100StateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        jLabel3.setText("Moedas");

        lblTotalN.setText("0,00");

        jLabel5.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        jLabel5.setText("Notas");

        jLabel13.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel13.setText("R$ 0,05:");

        jLabel12.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel12.setText("R$ 0,10:");

        jLabel14.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel14.setText("R$ 0,25:");

        jLabel15.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel15.setText("R$ 0,50:");

        jLabel16.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel16.setText("R$ 1,00:");

        spn005.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn005StateChanged(evt);
            }
        });

        spn01.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn01StateChanged(evt);
            }
        });

        spn025.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn025StateChanged(evt);
            }
        });

        spn05.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn05StateChanged(evt);
            }
        });

        spn1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn1StateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel6.setText("Total em moedas: R$");

        lblTotalM.setText("0,00");

        btnConfirmar.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dinheiro.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel9.setText("Total geral: R$");

        lblTotal.setText("0,00");

        jLabel29.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel29.setText("Valor a ser pago: R$");

        lblValorPago.setText("0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel26)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addComponent(spn10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel28))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spn20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spn50, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spn100, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(spn01, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(spn025, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(spn05, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(spn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(spn005, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(61, 61, 61)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalM, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnConfirmar)
                        .addGap(123, 123, 123)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel9)
                        .addGap(9, 9, 9)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblValorPago))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(spn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(spn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(spn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(spn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(spn50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(spn100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(lblTotalM)
                            .addComponent(lblTotalN)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(spn005, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(spn01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spn025, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spn05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(spn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addGap(134, 134, 134))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contabilizarDinheiroCaixa(Venda venda){
        CtrlCaixa caixa = new CtrlCaixa();
        venda.setCaixa(caixa.buscarCaixa());
        
        venda.getCaixa().getMoedas().setQtd5(venda.getCaixa().getMoedas().getQtd5() + venda.getTipoPagamento().getDinheiro().getMoedas().getQtd5());
        venda.getCaixa().getMoedas().setQtd10(venda.getCaixa().getMoedas().getQtd10() + venda.getTipoPagamento().getDinheiro().getMoedas().getQtd10());
        venda.getCaixa().getMoedas().setQtd25(venda.getCaixa().getMoedas().getQtd25() + venda.getTipoPagamento().getDinheiro().getMoedas().getQtd25());
        venda.getCaixa().getMoedas().setQtd50(venda.getCaixa().getMoedas().getQtd50() + venda.getTipoPagamento().getDinheiro().getMoedas().getQtd50());
        venda.getCaixa().getMoedas().setQtd1Real(venda.getCaixa().getMoedas().getQtd1Real() + venda.getTipoPagamento().getDinheiro().getMoedas().getQtd1Real());
        
        venda.getCaixa().getNotas().setQtd2(venda.getCaixa().getNotas().getQtd2() + venda.getTipoPagamento().getDinheiro().getNotas().getQtd2());
        venda.getCaixa().getNotas().setQtd5(venda.getCaixa().getNotas().getQtd5() + venda.getTipoPagamento().getDinheiro().getNotas().getQtd5());
        venda.getCaixa().getNotas().setQtd10(venda.getCaixa().getNotas().getQtd10() + venda.getTipoPagamento().getDinheiro().getNotas().getQtd10());
        venda.getCaixa().getNotas().setQtd20(venda.getCaixa().getNotas().getQtd20() + venda.getTipoPagamento().getDinheiro().getNotas().getQtd20());
        venda.getCaixa().getNotas().setQtd50(venda.getCaixa().getNotas().getQtd50() + venda.getTipoPagamento().getDinheiro().getNotas().getQtd50());
        venda.getCaixa().getNotas().setQtd100(venda.getCaixa().getNotas().getQtd100() + venda.getTipoPagamento().getDinheiro().getNotas().getQtd100());
        
        caixa.alterarMoedasENotas(venda.getCaixa().getMoedas(), venda.getCaixa().getNotas());
    }
    
    private void valoresTotais(){
        double totalM = 0, totalN = 0, total = 0;
        totalM += (Double.parseDouble(spn005.getValue().toString()) * 0.05);
        totalM += (Double.parseDouble(spn01.getValue().toString()) * 0.1);
        totalM += (Double.parseDouble(spn025.getValue().toString()) * 0.25);
        totalM += (Double.parseDouble(spn05.getValue().toString()) * 0.5);
        totalM += (Double.parseDouble(spn1.getValue().toString()) * 1);
        
        totalN += (Double.parseDouble(spn2.getValue().toString()) * 2);
        totalN += (Double.parseDouble(spn5.getValue().toString()) * 5);
        totalN += (Double.parseDouble(spn10.getValue().toString()) * 10);
        totalN += (Double.parseDouble(spn20.getValue().toString()) * 20);
        totalN += (Double.parseDouble(spn50.getValue().toString()) * 50);
        totalN += (Double.parseDouble(spn100.getValue().toString()) * 100);
        total = totalN + totalM;
        
        lblTotalM.setText(String.format("%.2f", totalM));
        lblTotalN.setText(String.format("%.2f", totalN));
        lblTotal.setText(String.format("%.2f", total));
        
        totalEntrado = total;
    }
    
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(moedas != null){
            moedas.setQtd5((Integer)spn005.getValue());
            moedas.setQtd10((Integer)spn01.getValue());
            moedas.setQtd25((Integer)spn025.getValue());
            moedas.setQtd50((Integer)spn05.getValue());
            moedas.setQtd1Real((Integer)spn1.getValue());
            
            notas.setQtd2((Integer)spn2.getValue());
            notas.setQtd5((Integer)spn5.getValue());
            notas.setQtd10((Integer)spn10.getValue());
            notas.setQtd20((Integer)spn20.getValue());
            notas.setQtd50((Integer)spn50.getValue());
            notas.setQtd100((Integer)spn100.getValue());
            
            CtrlCaixa caixa = new CtrlCaixa();
            
            if(caixa.alterarMoedasENotas(moedas, notas)){
                JOptionPane.showMessageDialog(null, "Dinheiro inserido com sucesso!");
            }
            btnCancelar.doClick();
        }else if(venda != null){
            
            if((venda.getTipoPagamento().getValorDescontado().doubleValue() - totalEntrado) < 0.05 || (totalEntrado - venda.getTipoPagamento().getValorDescontado().doubleValue()) > -0.05){
                
                
                venda.getTipoPagamento().setCartao(null);
                venda.getTipoPagamento().getDinheiro().getMoedas().setQtd5((Integer)spn005.getValue());
                venda.getTipoPagamento().getDinheiro().getMoedas().setQtd10((Integer)spn01.getValue());
                venda.getTipoPagamento().getDinheiro().getMoedas().setQtd25((Integer)spn025.getValue());
                venda.getTipoPagamento().getDinheiro().getMoedas().setQtd50((Integer)spn05.getValue());
                venda.getTipoPagamento().getDinheiro().getMoedas().setQtd1Real((Integer)spn1.getValue());

                venda.getTipoPagamento().getDinheiro().getNotas().setQtd2((Integer)spn2.getValue());
                venda.getTipoPagamento().getDinheiro().getNotas().setQtd5((Integer)spn5.getValue());
                venda.getTipoPagamento().getDinheiro().getNotas().setQtd10((Integer)spn10.getValue());
                venda.getTipoPagamento().getDinheiro().getNotas().setQtd20((Integer)spn20.getValue());
                venda.getTipoPagamento().getDinheiro().getNotas().setQtd50((Integer)spn50.getValue());
                venda.getTipoPagamento().getDinheiro().getNotas().setQtd100((Integer)spn100.getValue());

                TipoPagamentoDAO tpDAO = new TipoPagamentoDAO(bd);
                if(tpDAO.inserir(venda.getTipoPagamento())){
                    venda.getTipoPagamento().setCodPagamento(tpDAO.proxCodigoExterno()- 1);


                    CtrlCliente ctrlCliente = new CtrlCliente();
                    Cliente aux = ctrlCliente.buscarCliente(venda.getCliente());
                    if(aux != null){
                        venda.setCliente(aux);
                        ctrl.cadastrarVenda(venda);

                        contabilizarDinheiroCaixa(venda);


                        btnCancelar.doClick();
                    }
            
                }
            }else{
                JOptionPane.showMessageDialog(null, "Entre com o valor correto");
                
            } 
            
        }
        
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        getContentPane().removeAll();
        this.dispose();
        getContentPane().setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void spn2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn2StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn2StateChanged

    private void spn5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn5StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn5StateChanged

    private void spn10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn10StateChanged
       valoresTotais();
    }//GEN-LAST:event_spn10StateChanged

    private void spn20StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn20StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn20StateChanged

    private void spn50StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn50StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn50StateChanged

    private void spn100StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn100StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn100StateChanged

    private void spn005StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn005StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn005StateChanged

    private void spn01StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn01StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn01StateChanged

    private void spn025StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn025StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn025StateChanged

    private void spn05StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn05StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn05StateChanged

    private void spn1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn1StateChanged
        valoresTotais();
    }//GEN-LAST:event_spn1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Look and Feel do sistema atual
       try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDinheiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalM;
    private javax.swing.JLabel lblTotalN;
    private javax.swing.JLabel lblValorPago;
    private javax.swing.JSpinner spn005;
    private javax.swing.JSpinner spn01;
    private javax.swing.JSpinner spn025;
    private javax.swing.JSpinner spn05;
    private javax.swing.JSpinner spn1;
    private javax.swing.JSpinner spn10;
    private javax.swing.JSpinner spn100;
    private javax.swing.JSpinner spn2;
    private javax.swing.JSpinner spn20;
    private javax.swing.JSpinner spn5;
    private javax.swing.JSpinner spn50;
    // End of variables declaration//GEN-END:variables
}
