/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CtrlCliente;
import Controller.CtrlMedicamento;
import Controller.CtrlVenda;
import Model.CartaoCredito;
import Model.Cliente;
import Model.Dinheiro;
import Model.MedQtd;
import Model.Medicamento;
import Model.Moedas;
import Model.Notas;
import Model.Venda;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.EmptyBorder;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mslda
 */
public class FrmVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVenda
     */
    
    CtrlVenda ctrl = new CtrlVenda();
    Venda venda = new Venda();
    CtrlMedicamento ctrlMedic = new CtrlMedicamento();
    CtrlCliente ctrlCliente = new CtrlCliente();
    Cliente cliente = new Cliente();
    Medicamento medic = new Medicamento();
    
    Vector dados = new Vector();
    //pra tbSelecionado
     int contador = 0;
    double valorTotal = 0, valorFinal;
    
    
    public FrmVenda() {
        initComponents();
        //Retirar bordas
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        setBorder(new EmptyBorder(new Insets(0,0,0,0))); 
        
        preencheTabelaSelec();
        
        lblParcelas.setEnabled(false);
        txtParcelas.setEditable(false);
        jLabel7.setEnabled(false);
        jLabel15.setEnabled(false);
        
        
        
        /*SOFTWARE DE CRISTAL, SE MEXER, QUEBRA*/
    }
    //centralizar o InternalFrame no DesktopPane
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    private void preencheTabelaSelec(){
        Vector head = new Vector();
        
         //colunas
        head.add("Nome");
        
        head.add("Qtd");
        
        head.add("Subtotal");
        
        DefaultTableModel modeloTabela = new DefaultTableModel(dados, head);
        tbSelecionado.setModel(modeloTabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbPagamento = new javax.swing.JComboBox<>();
        btnVenda = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblPorcentagem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMedicamentos = new javax.swing.JTable();
        txtBuscaCPF = new javax.swing.JFormattedTextField();
        btnBuscarCPF = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSelecionado = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblValorFinal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtParcelas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblParcelas = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel1.setText("Venda");

        jLabel2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel2.setText("Medicamento:");

        jLabel3.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel3.setText("Quantidade:");

        jLabel4.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel4.setText("Buscar cliente por CPF:");

        jLabel5.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel5.setText("Tipo de Pagamento:");

        jLabel6.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel6.setText("Porcentagem de Desconto:");

        cbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão de Credito" }));
        cbPagamento.setSelectedIndex(-1);
        cbPagamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPagamentoItemStateChanged(evt);
            }
        });

        btnVenda.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnVenda.setText("PROSSEGUIR");
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblPorcentagem.setText("0%");

        tbMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMedicamentosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbMedicamentos);

        btnBuscarCPF.setText("BUSCAR");
        btnBuscarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCPFActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel9.setText("Nome Cliente:");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel10.setText("Medicamentos:");

        tbSelecionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbSelecionado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSelecionadoMouseClicked(evt);
            }
        });
        tbSelecionado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbSelecionadoPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tbSelecionado);

        jLabel11.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel11.setText("Medicamentos selecionados: (Duplo clique para cancelar o item)");

        jLabel12.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel12.setText("Valor Total:  R$");

        lblValorTotal.setText("0,00");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Carrinho.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel13.setText("Valor Final: R$");

        lblValorFinal.setText("0,00");

        jLabel7.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel7.setText("Parcelas:");

        txtParcelas.setEditable(false);
        txtParcelas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtParcelasFocusLost(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel15.setText("Valor : R$");

        lblParcelas.setText("0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVenda)
                                .addGap(167, 167, 167)
                                .addComponent(btnCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnBuscarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbPagamento, 0, 160, Short.MAX_VALUE)
                                            .addComponent(txtParcelas))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblValorFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCPF))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(lblParcelas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblPorcentagem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblValorTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblValorFinal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVenda)
                    .addComponent(btnCancelar))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alteraTabelaSelec(Vector medVector){

        //dados.add(medVector);
        //instancia o modelo
        
        ((DefaultTableModel)tbSelecionado.getModel()).addRow(medVector);
        
        tbSelecionado.getColumnModel().getColumn(0).setPreferredWidth(180);
        tbSelecionado.getColumnModel().getColumn(1).setPreferredWidth(30);
        tbSelecionado.getColumnModel().getColumn(2).setPreferredWidth(80);
        
        tbSelecionado.setDefaultEditor(Object.class, null);
        
    }
    
    private void preencheTabelaMeds(){
        Vector head = new Vector();
        Vector dados = new Vector();
        
        //colunas
        head.add("Nome");
        
        head.add("Preço (R$)");
        
        head.add("Qtd");
        
        List<Medicamento> meds = ctrlMedic.listarMedicamento();
        
        
        
        
        for(Medicamento x : meds){
            Vector campoMeds = new Vector();
            
            campoMeds.add(x.getNome());
            
            campoMeds.add(x.getPreco());
            
            campoMeds.add(x.getQtdEstoque());
           
            dados.add(campoMeds);
        }
        
        //instancia o modelo
        DefaultTableModel modeloTabela = new DefaultTableModel(dados, head);
        
        tbMedicamentos.setModel(modeloTabela);
        tbMedicamentos.getColumnModel().getColumn(0).setPreferredWidth(180);
        tbMedicamentos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbMedicamentos.getColumnModel().getColumn(2).setPreferredWidth(30);
        
        tbMedicamentos.setDefaultEditor(Object.class, null);
        
    }
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        preencheTabelaMeds();
        //preencheTabelaSelec(medicamentos);
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtParcelasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtParcelasFocusLost
        double parcelas = valorFinal / Integer.parseInt(txtParcelas.getText());
        lblParcelas.setText(String.format("%.2f", parcelas));
    }//GEN-LAST:event_txtParcelasFocusLost

    private void tbSelecionadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbSelecionadoPropertyChange

        tbSelecionado.getModel().addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent e) {

                if (e.getType()==TableModelEvent.INSERT || e.getType()==TableModelEvent.DELETE) {
                    valorTotal = 0;
                    for(int x = 0; x < tbSelecionado.getModel().getRowCount(); x++){
                        double precos = Double.parseDouble(tbSelecionado.getModel().getValueAt(x, 2).toString());

                        valorTotal += precos;

                    }

                    lblValorTotal.setText(String.format("%.2f", valorTotal));

                    

                    if(lblPorcentagem.getText().equals("20%")){
                        valorFinal = valorTotal * 0.8;
                    }else if(lblPorcentagem.getText().equals("5%")){
                        valorFinal = valorTotal * 0.95;
                    }else{
                        valorFinal = valorTotal;
                    }

                    lblValorFinal.setText(String.format("%.2f", valorFinal));

                }
                //pegar o valor total na inserção dos dados no tablemodel, e pegar o valor final na alteração do porcentagem desconto

            }
        });
    }//GEN-LAST:event_tbSelecionadoPropertyChange

    private void tbSelecionadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSelecionadoMouseClicked
        if(evt.getClickCount() == 2){
            int linha = tbSelecionado.getSelectedRow();
            //dados.removeElementAt(linha);
            ((DefaultTableModel)tbSelecionado.getModel()).removeRow(linha);

        }
    }//GEN-LAST:event_tbSelecionadoMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        medic.setNome(txtMedicamento.getText());
        int qtd = Integer.parseInt(txtQuantidade.getText());

        Medicamento aux = ctrlMedic.buscarMedicamento(medic);
        if(aux != null){
            medic = aux;
            if(medic.getQtdEstoque() >= qtd){
                Vector medicamentos = new Vector();
                medicamentos.add(medic.getNome());
                medicamentos.add(qtd);
                medicamentos.add(medic.getPreco().multiply(new BigDecimal(qtd)));
                alteraTabelaSelec(medicamentos);

                //medicamentos.removeAllElements();

            }else{
                JOptionPane.showMessageDialog(null, "Quantidade superior a disponivel");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCPFActionPerformed
        cliente.setCpf(txtBuscaCPF.getText());
        Cliente aux = ctrlCliente.buscarCliente(cliente);
        if(aux != null){
            cliente = aux;
            txtNome.setText(aux.getNome());
            if(cliente.isAposentado()){
                lblPorcentagem.setText("20%");
                
                valorFinal = valorTotal * 0.8;
                lblValorFinal.setText(String.format("%.2f", valorFinal));
            }
        }else{
            //limpar();
        }
    }//GEN-LAST:event_btnBuscarCPFActionPerformed

    private void tbMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMedicamentosMouseClicked

        int linha = tbMedicamentos.getSelectedRow();

        txtMedicamento.setText(tbMedicamentos.getModel().getValueAt(linha, 0).toString());
    }//GEN-LAST:event_tbMedicamentosMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        getContentPane().removeAll();
        this.dispose();
        getContentPane().setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        int linhas = ((DefaultTableModel)tbSelecionado.getModel()).getRowCount();
        ArrayList<MedQtd> medqtd = new ArrayList();
        for(int x = 0; x < linhas; x++){
            MedQtd med = new MedQtd();
            med.getMedicamento().setNome(((DefaultTableModel)tbSelecionado.getModel()).getValueAt(x, 0).toString());
            med.setQuantidade(Integer.parseInt(((DefaultTableModel)tbSelecionado.getModel()).getValueAt(x, 1).toString()));

            medqtd.add(med);
        }

        if(lblPorcentagem.getText().equals("20%")){
            venda.setPorcentagemDesconto(20);
        }else if(lblPorcentagem.getText().equals("5%")){
            venda.setPorcentagemDesconto(5);
        }else{
            venda.setPorcentagemDesconto(0);
        }

        venda.setMedQtd(medqtd);
        venda.getCliente().setCpf(txtBuscaCPF.getText());
        venda.getCliente().setNome(txtNome.getText());
        venda.getTipoPagamento().setValor(new BigDecimal(valorTotal));
        venda.getTipoPagamento().setValorDescontado(new BigDecimal(valorFinal));

        if(cbPagamento.getSelectedItem().equals("Dinheiro")){
            venda.getTipoPagamento().setDinheiro(new Dinheiro());
            
            FrmDinheiro fDinheiro = new FrmDinheiro(venda);
            getContentPane().removeAll();
            getContentPane().setBackground(new Color(204,204,204));
            getContentPane().add(fDinheiro);
            fDinheiro.setVisible(true);
        }else if(cbPagamento.getSelectedItem().equals("Cartão de Credito")){
            venda.getTipoPagamento().setCartao(new CartaoCredito());
            venda.getTipoPagamento().getCartao().setParcelas(Integer.parseInt(txtParcelas.getText()));
            FrmCartao fCartao = new FrmCartao(venda);
            getContentPane().removeAll();
            getContentPane().setBackground(new Color(204,204,204));
            getContentPane().add(fCartao);
            fCartao.setVisible(true);
        }
    }//GEN-LAST:event_btnVendaActionPerformed

    private void cbPagamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPagamentoItemStateChanged
        double valor = 0;
        if(cliente.isAposentado()){
            lblPorcentagem.setText("20%");
            valorFinal = valorTotal * 0.8;

        }else if(cbPagamento.getSelectedItem().equals("Dinheiro")){
            lblPorcentagem.setText("5%");
            valorFinal = valorTotal * 0.95;
            

        }else{
            lblPorcentagem.setText("0%");
            valorFinal = valorTotal;
        }
        
        if((cbPagamento.getSelectedItem().equals("Cartão de Credito"))){
            lblParcelas.setEnabled(true);
            txtParcelas.setEditable(true);
            jLabel7.setEnabled(true);
            jLabel15.setEnabled(true);
        }else if(cbPagamento.getSelectedItem().equals("Dinheiro")){
            lblParcelas.setEnabled(false);
            txtParcelas.setEditable(false);
            jLabel7.setEnabled(false);
            jLabel15.setEnabled(false);
        }
        lblValorFinal.setText(String.format("%.2f", valorFinal));
    }//GEN-LAST:event_cbPagamentoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarCPF;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVenda;
    private javax.swing.JComboBox<String> cbPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblParcelas;
    private javax.swing.JLabel lblPorcentagem;
    private javax.swing.JLabel lblValorFinal;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTable tbMedicamentos;
    private javax.swing.JTable tbSelecionado;
    private javax.swing.JFormattedTextField txtBuscaCPF;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtParcelas;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
